//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DefLink
{
    using System;
    using System.Collections.Generic;
    
    public partial class VPN
    {
        public int ID_VPN { get; set; }
        public Nullable<int> ID_Subscription { get; set; }
        public string UUID { get; set; }
        public string ServerAddress { get; set; }
        public string PublicKey { get; set; }
        public string Label { get; set; }
    
        public virtual Subscription Subscription { get; set; }
    }
}
